/*
  # Seed Mock Candidate Profiles

  1. Inserts 8 mock candidate profiles with realistic data
  2. Includes all profile information needed for list and detail views
*/

INSERT INTO profiles (
  name, title, company, experience, location, score, about, skills,
  education, work_history, website, resume_url, email, social_links,
  ideal_next_opportunity, lpa, club_member, availability
) VALUES
(
  'Ashwin Kumar',
  'Product Designer',
  'Zepto',
  '0 - 1 Years of Experience',
  'New Delhi, India',
  80,
  'I''m excited about building product that have a big impact. Also, I''m looking for opportunities that can move faster and have more ownership to the product. Lastly I value opportunity of learning new technology a lot. So I''m looking for opportunity of learning new coworker who I can learn from also.',
  ARRAY['UX design', 'UI Design', 'Motion Design', 'UX Research', 'UX Thought Process', 'Critical Thinking', 'Prototype', 'Problem Solving'],
  '[{"school": "Indian Institute of Technology (IIT)", "degree": "Bachelor of Computer Science Engineering", "years": "Jan 2021 - Jan 2025"}]',
  '[{"title": "Product Designer II", "company": "Xflow Technologies", "duration": "Jan 2025 - Present"}, {"title": "Product Designer I", "company": "Xflow Technologies", "duration": "May 2024 - Dec 2024"}, {"title": "Product Design Intern", "company": "Remitly", "duration": "Jan 2024 - Mar 2024"}]',
  'ashwin.com',
  'https://example.com/ashwin-resume.pdf',
  'hi@ashwinkumar.com',
  '{"linkedin": "https://linkedin.com/in/ashwin"}',
  'Product Designer 2',
  '13 LPA',
  false,
  'Available Immediately'
),
(
  'Priya Sharma',
  'Product Designer',
  'Zapier',
  '1 - 3 Years of Experience',
  'Bangalore, India',
  85,
  'Passionate about creating intuitive user experiences and solving complex design problems. Looking for roles that value design thinking and collaboration.',
  ARRAY['UI Design', 'User Research', 'Prototyping', 'Figma', 'Design Systems', 'Interaction Design', 'Accessibility'],
  '[{"school": "National Institute of Design", "degree": "Master of Design", "years": "2020 - 2022"}]',
  '[{"title": "Senior Designer", "company": "Zapier", "duration": "Jun 2023 - Present"}, {"title": "Product Designer", "company": "Freshworks", "duration": "Jan 2022 - May 2023"}]',
  'priyasharma.design',
  'https://example.com/priya-resume.pdf',
  'priya@designstudio.com',
  '{"linkedin": "https://linkedin.com/in/priya-sharma", "dribbble": "https://dribbble.com/priya"}',
  'Lead Designer',
  '18 LPA',
  true,
  'Available in 2 weeks'
),
(
  'Rajesh Patel',
  'Product Designer',
  'Unacademy',
  '2 - 4 Years of Experience',
  'Mumbai, India',
  75,
  'Design-focused professional with strong emphasis on user research and data-driven decisions. Excited about edtech and building products for scale.',
  ARRAY['Product Design', 'UX Research', 'Data Analysis', 'Wireframing', 'User Testing', 'Design Sprints'],
  '[{"school": "SVKM''s NMIMS University", "degree": "Bachelor of Design", "years": "2016 - 2020"}]',
  '[{"title": "Product Designer", "company": "Unacademy", "duration": "Aug 2021 - Present"}, {"title": "UX Designer", "company": "Flipkart", "duration": "Jun 2020 - Jul 2021"}]',
  'rajeshpatel.com',
  'https://example.com/rajesh-resume.pdf',
  'rajesh@edtech.com',
  '{"linkedin": "https://linkedin.com/in/rajesh-patel"}',
  'Senior Product Designer',
  '22 LPA',
  false,
  'Available Immediately'
),
(
  'Neha Gupta',
  'Product Designer',
  'Swiggy',
  '3 - 5 Years of Experience',
  'Pune, India',
  90,
  'Experienced designer with a track record of shipping products used by millions. Strong in systems thinking and cross-functional collaboration.',
  ARRAY['Design Systems', 'Product Strategy', 'Team Leadership', 'Mobile Design', 'Web Design', 'Analytics', 'Design Thinking'],
  '[{"school": "Anna University", "degree": "B.Tech in Information Technology", "years": "2015 - 2019"}]',
  '[{"title": "Senior Product Designer", "company": "Swiggy", "duration": "Mar 2022 - Present"}, {"title": "Product Designer", "company": "OYO", "duration": "Jan 2020 - Feb 2022"}, {"title": "Junior Designer", "company": "Myntra", "duration": "Jun 2019 - Dec 2019"}]',
  'nehagupta.design',
  'https://example.com/neha-resume.pdf',
  'neha@product.com',
  '{"linkedin": "https://linkedin.com/in/neha-gupta", "twitter": "https://twitter.com/neha_designs"}',
  'Design Lead',
  '28 LPA',
  true,
  'Available in 1 month'
),
(
  'Akshay Verma',
  'Product Designer',
  'PhonePe',
  '1 - 2 Years of Experience',
  'Hyderabad, India',
  82,
  'Fintech enthusiast focused on creating accessible financial products. Strong foundation in design systems and component thinking.',
  ARRAY['UX Design', 'Financial Design', 'Mobile UI', 'Design Systems', 'Usability Testing'],
  '[{"school": "IIT Madras", "degree": "Bachelor of Computer Science", "years": "2018 - 2022"}]',
  '[{"title": "Product Designer", "company": "PhonePe", "duration": "Jul 2022 - Present"}, {"title": "Design Intern", "company": "PayPal", "duration": "Jan 2022 - Jun 2022"}]',
  'akshayverma.design',
  'https://example.com/akshay-resume.pdf',
  'akshay@fintech.com',
  '{"linkedin": "https://linkedin.com/in/akshay-verma"}',
  'Senior Product Designer',
  '20 LPA',
  false,
  'Available Immediately'
),
(
  'Divya Kesavan',
  'Product Designer',
  'Microsoft',
  '4 - 6 Years of Experience',
  'Bangalore, India',
  88,
  'International experience in building enterprise and consumer products. Expert in design processes and mentoring junior designers.',
  ARRAY['Enterprise UX', 'Consumer Design', 'Research', 'Mentoring', 'Design Leadership', 'Accessibility Standards'],
  '[{"school": "Manipal University", "degree": "Bachelor of Information Technology", "years": "2014 - 2018"}]',
  '[{"title": "Senior Designer", "company": "Microsoft", "duration": "May 2021 - Present"}, {"title": "Designer", "company": "IBM", "duration": "Aug 2018 - Apr 2021"}]',
  'divyakesavan.com',
  'https://example.com/divya-resume.pdf',
  'divya@microsoft.com',
  '{"linkedin": "https://linkedin.com/in/divya-kesavan", "behance": "https://behance.net/divya"}',
  'Design Manager',
  '32 LPA',
  true,
  'Available in 1.5 months'
),
(
  'Vikram Singh',
  'Product Designer',
  'Amazon',
  '2 - 3 Years of Experience',
  'Delhi, India',
  79,
  'E-commerce design specialist with expertise in conversion optimization. Passionate about data-driven design and A/B testing.',
  ARRAY['E-commerce Design', 'Conversion Optimization', 'A/B Testing', 'Analytics', 'User Flows'],
  '[{"school": "Delhi University", "degree": "Bachelor of Arts", "years": "2016 - 2019"}]',
  '[{"title": "Product Designer", "company": "Amazon", "duration": "Sep 2021 - Present"}, {"title": "UX Designer", "company": "Snapdeal", "duration": "Mar 2020 - Aug 2021"}]',
  'vikramsingh.design',
  'https://example.com/vikram-resume.pdf',
  'vikram@ecommerce.com',
  '{"linkedin": "https://linkedin.com/in/vikram-singh"}',
  'Senior Product Designer',
  '24 LPA',
  false,
  'Available in 3 weeks'
),
(
  'Ananya Mehta',
  'Product Designer',
  'Google',
  '5+ Years of Experience',
  'Gurugram, India',
  92,
  'Design leader with international experience at top tech companies. Specialized in AI/ML product design and large-scale systems.',
  ARRAY['Design Leadership', 'AI/ML Design', 'Large Scale Systems', 'Design Strategy', 'Team Management', 'Innovation'],
  '[{"school": "IIIT Hyderabad", "degree": "Master of Computer Science", "years": "2013 - 2015"}]',
  '[{"title": "Senior Design Manager", "company": "Google", "duration": "Jan 2021 - Present"}, {"title": "Senior Designer", "company": "Apple", "duration": "Jun 2018 - Dec 2020"}, {"title": "Product Designer", "company": "Uber", "duration": "Jul 2016 - May 2018"}]',
  'ananyamehta.design',
  'https://example.com/ananya-resume.pdf',
  'ananya@tech.com',
  '{"linkedin": "https://linkedin.com/in/ananya-mehta", "twitter": "https://twitter.com/ananya_designs", "dribbble": "https://dribbble.com/ananya"}',
  'Director of Design',
  '45 LPA',
  true,
  'Available in 2 months'
);
